routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() {
    return redirect(route('articles.index'));
});
Route::resources([
    'articles' => 'ArticlesController'
]);

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'title', 'description', 'image', 'category_id'
    ];

    protected $hidden = [
        'created_at', 'updated_at', 'id', 'category_id'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    static function last_5($category_id)
    {
        return \App\Models\Article::where('category_id', $category_id)->orderBy('created_at')->take(5)->get();
    }

}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'title'
    ];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Api/ArticlesController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    public function last_5(Request $request)
    {
        $request->validate([
            'category' => 'required|numeric'
        ]);
        $articles = \App\Models\Article::last_5($request->category);

        if($articles->count() == 0) {
            return 'end';
        } else {
            return $articles->toJson();
        }
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Article;

class ArticlesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = \App\Models\Article::orderBy('created_at', 'desc')->get();
        return view('index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = \App\Models\Category::all();
        return view('create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'category_id' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg'
        ]);

        $request->hasFile('image') ? $url = \Storage::disk('public')->putFile('images', $request->image) : $url = null;

        \App\Models\Article::create([
            'title' => $request->title,
            'category_id' => $request->category_id,
            'image' => $url,
            'description' => $request->description ? $request->description : null
        ]);

        return redirect(route('articles.index'))->with('success', 'Статья успешно добавлена');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(\App\Models\Article $article)
    {
        $categories = \App\Models\Category::all();
        return view('edit', compact('article', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, \App\Models\Article $article)
    {
        $request->validate([
            'title' => 'required',
            'category_id' => 'required',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg'
        ]);
        if($request->hasFile('image') && $article->image) {
            \Storage::delete($article->image);
            $url = \Storage::disk('public')->putFile('image', $request->image);
            $article->image = $url;
        }
        $article->title = $request->title;
        $article->description = $request->description;
        $article->category_id = $request->category_id;
        $article->save();

        return redirect(route('articles.index'))->with('success', 'Статья успешно обновлена');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/create.blade.php
@extends('layout')

@section('title')
    Добавление статьи
@endsection

@section('content')
    <form action="{{ route('articles.store') }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label>Заголовок</label>
            <input type="text" name="title" class="form-control">
        </div>
        <div class="form-group">
            <label>Категория</label>
            <select class="form-control" name="category_id">
                @foreach ($categories as $key => $category)
                    <option value="{{ $category->id }}">{{ $category->title }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label>Описание</label>
            <textarea class="form-control" name="description"></textarea>
            <small>Необязательно</small>
        </div>
        <div class="form-group">
            <label>Изображение</label>
            <input type="file" class="form-control-file" name="image">
        </div>
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
@endsection

resources/views/edit.blade.php
@extends('layout')

@section('title')
    Добавление статьи
@endsection

@section('content')
    <form action="{{ route('articles.update', $article) }}" method="post" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
            <label>Заголовок</label>
            <input type="text" name="title" class="form-control" value="{{ $article->title }}">
        </div>
        <div class="form-group">
            <label>Категория</label>
            <select class="form-control" name="category_id">
                @foreach ($categories as $key => $category)
                    <option value="{{ $category->id }}" @if($article->category->id == $category->id) selected @endif>{{ $category->title }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label>Описание</label>
            <textarea class="form-control" name="description">{{ $article->description }}</textarea>
            <small>Необязательно</small>
        </div>
        <div class="form-group">
            <label>Изображение</label>
            @if($article->image)<img src="{{ Storage::url($article->image) }}" alt="">@endif
            <input type="file" class="form-control-file" name="image">
        </div>
        <button type="submit" class="btn btn-primary">Обновить</button>
    </form>
@endsection

resources/views/index.blade.php
@extends('layout')

@section('title')
    Главная
@endsection

@section('content')
    <table class="table">
        <thead>
            <tr>
                <th>№</th>
                <th>Заголовок</th>
                <th>Категория</th>
                <th>Описание</th>
                <th>Изображение</th>
                <th></th>
            </tr>
            <tbody>
                @foreach ($articles as $key => $article)
                    <tr>
                        <td>{{ $article->id }}</td>
                        <td>{{ $article->title }}</td>
                        <td>{{ $article->category->title }}</td>
                        <td>{{ $article->description }}</td>
                        <td><img src="{{ Storage::url($article->image) }}" alt="" class="img-thumbnail" style="max-width: 150px"></td>
                        <td><a href="{{ route('articles.edit', ['article' => $article]) }}" class="btn btn-sm btn-success">Редактировать</a></td>
                    </tr>
                @endforeach
            </tbody>
        </thead>
    </table>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top mb-3">
        <a class="navbar-brand" href="#">Regium</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item @if(Route::is('articles.index')) active @endif">
                    <a class="nav-link" href="{{ route('articles.index') }}">Главная</a>
                </li>
                <li class="nav-item @if(Route::is('articles.create')) active @endif">
                    <a class="nav-link" href="{{ route('articles.create') }}">Добавить</a>
                </li>
            </ul>
        </div>
    </nav>

    @if(session()->has('success'))
        <div class="alert alert-success alert-dismissible fade show mb-3" role="alert">
            {!! session()->get('success')!!}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if(session()->has('error'))
        <div class="alert alert-danger alert-dismissible fade show mb-3" role="alert">
            {!! session()->get('error')!!}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    @endif
    @if ($errors->any())
    <div class="alert alert-warning fade show mb-3" role="alert">
            @foreach ($errors->all() as $error)
                {{ $error }}
            @endforeach
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
    </div>
    @endif

    <main role="main" class="container">

        @yield('content')

    </main>
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>